name: machine info

on: [push] 

jobs:
    check-version:
        runs-on: ubuntu-latest
        steps:
            - name: processor info
              run: |
                import platform
                print(platform.processor()
              shell: python